import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { Button, ButtonGroup, Box, Grid, GridItem } from '@chakra-ui/react'
import ListaIcon from '../Components/ListaIcon'
import { IoLogoJavascript, IoLogoHtml5 } from 'react-icons/io'
import { SiPostgresql, SiRedux, SiVercel } from 'react-icons/si'
import { DiReact } from 'react-icons/di'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Dogs - Con Librerias</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <Grid
          h='200px'
          templateRows='repeat(2, 1fr)'
          templateColumns='repeat(6, 1fr)'
          gap={4}
        >
          <GridItem rowSpan={1} colSpan={6} bg='tomato'>
            <h1 className={styles.title}>
              Practica de conexión de DB, API y estilos con CHACKRA UI.
            </h1>
            <Link href={'/dogs'}>
              <Button>
                Entrar!
              </Button>
            </Link>

          </GridItem>
          <GridItem colSpan={3} bg='papayawhip'>
            <Grid
              h='200px'
              templateRows='repeat(2, 1fr)'
              templateColumns='repeat(6, 1fr)'
              gap={4}
            >
              <GridItem rowSpan={1} colSpan={6} bg='tomato' align='center' alignItems={'center'}>
                <h2>Tecnologia Utilizada</h2>
              </GridItem>
              <GridItem colSpan={3} bg='papayawhip'>
                <ListaIcon iconos={[{ icono: IoLogoHtml5, text: "HTML5" }, { icono: IoLogoJavascript, text: "Javascript" }]} />
              </GridItem>
              <GridItem colSpan={3} bg='papayawhip'>
                <ListaIcon iconos={[{ icono: SiPostgresql, text: "Postgresql" }, { icono: SiRedux, text: "Redux" }, { icono: SiVercel, text: "Vercel" }]} />
              </GridItem>
            </Grid>

          </GridItem>
          <GridItem colSpan={3} bg='papayawhip'>
            
          </GridItem>          
        </Grid>



      </main>




      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
